In [53]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import string

In [71]:
df = pd.read_csv("../Supervised Learning/Data Sets/emotions.csv",header=None,names=['text','emotion'])

In [72]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [73]:
df.isna().sum()

text       0
emotion    0
dtype: int64

In [74]:
unique_emotions=df['emotion'].unique()

In [75]:
d={}
i=0
for j in unique_emotions:
    d[j] = i
    i+=1

In [76]:
df['emotion']=df['emotion'].map(d)

In [77]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [78]:
# Convert to lower case 
df['text'] = df['text'].apply(lambda x:x.lower())

In [62]:
# Remove punctuations

def rm_pn(x):
    return x.translate(str.maketrans('','',string.punctuation))

df['text'] = df['text'].apply(rm_pn)

In [63]:
# Remove numbers 

def rm_num(x):
    txt=""
    for i in x:
        if(not i.isdigit()):
            txt+=i
    return txt

df['text'] = df['text'].apply(rm_num)

In [64]:
# Remove emojies

def rm_emo(x):
    txt=""
    for i in x:
        if(not i.isascii()):
            txt+=i
    return txt

df['text'] = df['text'].apply(rm_emo)

In [79]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [65]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [66]:
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to C:\Users\BHUMIT
[nltk_data]     SINGH\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\BHUMIT
[nltk_data]     SINGH\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [67]:
stop_words = set(stopwords.words('english'))

In [84]:
# Tokenizing

def rm_stop(x):
    arr = word_tokenize(x)
    cleaned=[]
    for i in arr:
        if(not i in stop_words):
            cleaned.append(i)
    return " ".join(cleaned)

In [85]:
df['text']=df['text'].apply(rm_stop)

In [87]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1