In [14]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras import layers

In [15]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [16]:
df.head()

   soil_moisture  temperature_c  sunlight_hours  needs_water
0           0.10             34               9            1
1           0.15             30               8            1
2           0.20             26               7            1
3           0.25             22               4            0
4           0.40             28               8            0

In [17]:
X_raw = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [18]:
scalar = MinMaxScaler() # Normalization

# X_min = X.min()
# X_max = X.max()
# X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [19]:
X_raw

    soil_moisture  temperature_c  sunlight_hours
0            0.10             34               9
1            0.15             30               8
2            0.20             26               7
3            0.25             22               4
4            0.40             28               8
5            0.60             30              10
6            0.35             19               3
7            0.18             22              10
8            0.45             35              12
9            0.05             24               5
10           0.80             33               9
11           0.27             33              11
12           0.55             21               2
13           0.70             25               6
14           0.12             20               1
15           0.30             29               9

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X_raw, y, test_size=0.33, random_state=42)

In [21]:
model = keras.Sequential([
    layers.Input(shape =( X_train.shape[1],)),
    layers.Dense(8,activation="relu"),
    layers.Dense(1,activation='sigmoid')
])

In [22]:
model.compile(optimizer="sgd",loss="binary_crossentropy",metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [23]:
history = model.fit(
    X_train , y_train,
    validation_data=(X_test,y_test),
    epochs=100,
    batch_size=4,
    verbose=1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 3s 250ms/step - accuracy: 0.8000 - loss: 0.6389 - val_accuracy: 0.5000 - val_loss: 0.9102
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.4000 - loss: 0.9854 - val_accuracy: 0.3333 - val_loss: 1.7486
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.7000 - loss: 0.6347 - val_accuracy: 0.5000 - val_loss: 0.9037
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6000 - loss: 0.7067 - val_accuracy: 0.3333 - val_loss: 1.7572
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.6000 - loss: 0.6973 - val_accuracy: 0.3333 - val_loss: 1.2265
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.7000 - loss: 0.8029 - val_accuracy: 0.5000 - val_loss: 0.9197
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.7000 - loss: 0.6342 - val_accuracy: 0.6667 - val_loss: 0.9285
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5000 - loss: 0.7579 - val_accuracy: 0.3333 - val_loss: 2.6639
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.7000 - loss: 0.9971 - val_accuracy: 0.3333 - val_loss: 1.5227
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.7000 - loss: 0.6671 - val_accuracy: 0.3333 - val_loss: 1.5454
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.7000 - loss: 0.7403 - val_accuracy: 0.3333 - val_loss: 1.0609
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.6000 - loss: 0.6626 - val_accuracy: 0.3333 - val_loss: 0.9176
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.7000 - loss: 0.5867 - val_accuracy: 0.3333 - val_loss: 1.0397
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.6000 - loss: 0.5839 - val_accuracy: 0.3333 - val_loss: 1.2759
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.7000 - loss: 0.6575 - val_accuracy: 0.3333 - val_loss: 1.8126
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6000 - loss: 0.8239 - val_accuracy: 0.3333 - val_loss: 1.7507
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.7000 - loss: 0.6613 - val_accuracy: 0.3333 - val_loss: 0.9692
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6000 - loss: 0.6142 - val_accuracy: 0.3333 - val_loss: 1.6286
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.6000 - loss: 0.7001 - val_accuracy: 0.3333 - val_loss: 1.4928
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 0.7000 - loss: 0.6143 - val_accuracy: 0.3333 - val_loss: 0.9141
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6000 - loss: 0.5958 - val_accuracy: 0.3333 - val_loss: 1.4256
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7000 - loss: 0.6553 - val_accuracy: 0.3333 - val_loss: 1.0897
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7000 - loss: 0.6050 - val_accuracy: 0.5000 - val_loss: 0.8424
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6000 - loss: 0.6682 - val_accuracy: 0.6667 - val_loss: 0.9315
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6000 - loss: 0.6249 - val_accuracy: 0.3333 - val_loss: 1.3978
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.7000 - loss: 0.5995 - val_accuracy: 0.3333 - val_loss: 0.9479
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7540 - val_accuracy: 0.3333 - val_loss: 1.8675
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6000 - loss: 0.7657 - val_accuracy: 0.3333 - val_loss: 1.2497
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7000 - loss: 0.6050 - val_accuracy: 0.6667 - val_loss: 0.8781
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6000 - loss: 0.7297 - val_accuracy: 0.3333 - val_loss: 1.3384
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6000 - loss: 0.6424 - val_accuracy: 0.3333 - val_loss: 1.3588
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.7000 - loss: 0.6548 - val_accuracy: 0.3333 - val_loss: 1.3250
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7000 - loss: 0.6462 - val_accuracy: 0.5000 - val_loss: 0.7880
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.3000 - loss: 0.7725 - val_accuracy: 0.5000 - val_loss: 0.7915
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.6000 - loss: 0.7419 - val_accuracy: 0.3333 - val_loss: 1.1733
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.7000 - loss: 0.5877 - val_accuracy: 0.6667 - val_loss: 0.8729
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.7000 - loss: 0.6200 - val_accuracy: 0.3333 - val_loss: 0.9080
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6000 - loss: 0.6542 - val_accuracy: 0.3333 - val_loss: 0.9826
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7274 - val_accuracy: 0.3333 - val_loss: 1.4898
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.7000 - loss: 0.6294 - val_accuracy: 0.3333 - val_loss: 1.0920
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7000 - loss: 0.6085 - val_accuracy: 0.3333 - val_loss: 1.0771
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.6000 - loss: 0.5874 - val_accuracy: 0.3333 - val_loss: 1.2795
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.6000 - loss: 0.6289 - val_accuracy: 0.3333 - val_loss: 1.4245
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7000 - loss: 0.6757 - val_accuracy: 0.5000 - val_loss: 0.8109
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5000 - loss: 0.6580 - val_accuracy: 0.3333 - val_loss: 1.1236
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.6000 - loss: 0.6416 - val_accuracy: 0.3333 - val_loss: 1.2787
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7000 - loss: 0.6596 - val_accuracy: 0.3333 - val_loss: 1.1570
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7000 - loss: 0.5855 - val_accuracy: 0.3333 - val_loss: 1.0533
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.6000 - loss: 0.6007 - val_accuracy: 0.3333 - val_loss: 1.0716
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.7000 - loss: 0.5956 - val_accuracy: 0.3333 - val_loss: 1.2176
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.7000 - loss: 0.5851 - val_accuracy: 0.3333 - val_loss: 1.1001
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6000 - loss: 0.5957 - val_accuracy: 0.3333 - val_loss: 1.0924
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.7000 - loss: 0.5754 - val_accuracy: 0.3333 - val_loss: 0.9628
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6000 - loss: 0.6093 - val_accuracy: 0.5000 - val_loss: 1.0098
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6000 - loss: 0.5929 - val_accuracy: 0.3333 - val_loss: 0.9837
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.6000 - loss: 0.5841 - val_accuracy: 0.3333 - val_loss: 1.0466
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.6000 - loss: 0.6121 - val_accuracy: 0.5000 - val_loss: 0.9363
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - accuracy: 0.5000 - loss: 0.6104 - val_accuracy: 0.3333 - val_loss: 0.9730
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6000 - loss: 0.6016 - val_accuracy: 0.6667 - val_loss: 0.9045
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7000 - loss: 0.6115 - val_accuracy: 0.3333 - val_loss: 1.1227
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7000 - loss: 0.5917 - val_accuracy: 0.3333 - val_loss: 0.9578
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.6000 - loss: 0.7048 - val_accuracy: 0.5000 - val_loss: 0.8510
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6000 - loss: 0.6095 - val_accuracy: 0.3333 - val_loss: 1.2099
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.7000 - loss: 0.5765 - val_accuracy: 0.3333 - val_loss: 1.1073
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.6000 - loss: 0.5995 - val_accuracy: 0.3333 - val_loss: 1.3008
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7000 - loss: 0.6001 - val_accuracy: 0.3333 - val_loss: 0.9982
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.5927 - val_accuracy: 0.3333 - val_loss: 1.4065
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7000 - loss: 0.6023 - val_accuracy: 0.3333 - val_loss: 1.0699
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.6000 - loss: 0.5907 - val_accuracy: 0.3333 - val_loss: 1.2465
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7000 - loss: 0.5870 - val_accuracy: 0.3333 - val_loss: 1.1950
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.6000 - loss: 0.5977 - val_accuracy: 0.3333 - val_loss: 1.2731
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7000 - loss: 0.6393 - val_accuracy: 0.3333 - val_loss: 1.0209
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7000 - loss: 0.6092 - val_accuracy: 0.3333 - val_loss: 1.1328
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6000 - loss: 0.7013 - val_accuracy: 0.3333 - val_loss: 1.2009
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7000 - loss: 0.6305 - val_accuracy: 0.3333 - val_loss: 1.0782
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6000 - loss: 0.6143 - val_accuracy: 0.5000 - val_loss: 0.8404
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.6000 - loss: 0.6782 - val_accuracy: 0.5000 - val_loss: 0.8332
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.5000 - loss: 0.7018 - val_accuracy: 0.3333 - val_loss: 1.0948
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.7000 - loss: 0.5732 - val_accuracy: 0.3333 - val_loss: 1.0106
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.6000 - loss: 0.5743 - val_accuracy: 0.3333 - val_loss: 0.9981
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.6000 - loss: 0.6514 - val_accuracy: 0.6667 - val_loss: 0.9264
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6178 - val_accuracy: 0.3333 - val_loss: 1.1231
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.7000 - loss: 0.6217 - val_accuracy: 0.6667 - val_loss: 0.9545
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6000 - loss: 0.6367 - val_accuracy: 0.5000 - val_loss: 0.8551
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6000 - loss: 0.6374 - val_accuracy: 0.6667 - val_loss: 0.8763
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6000 - loss: 0.6249 - val_accuracy: 0.3333 - val_loss: 1.1800
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7000 - loss: 0.6572 - val_accuracy: 0.3333 - val_loss: 1.1735
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7000 - loss: 0.5915 - val_accuracy: 0.3333 - val_loss: 1.2169
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7000 - loss: 0.5910 - val_accuracy: 0.3333 - val_loss: 1.0001
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - accuracy: 0.6000 - loss: 0.5883 - val_accuracy: 0.3333 - val_loss: 0.9844
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6000 - loss: 0.5943 - val_accuracy: 0.6667 - val_loss: 0.9361
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6000 - loss: 0.6442 - val_accuracy: 0.3333 - val_loss: 1.1694
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7000 - loss: 0.5930 - val_accuracy: 0.3333 - val_loss: 1.1937
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7000 - loss: 0.6174 - val_accuracy: 0.3333 - val_loss: 1.0128
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6000 - loss: 0.5782 - val_accuracy: 0.3333 - val_loss: 1.1251
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7000 - loss: 0.5669 - val_accuracy: 0.3333 - val_loss: 1.1428
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7000 - loss: 0.5782 - val_accuracy: 0.3333 - val_loss: 1.0174
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7000 - loss: 0.5685 - val_accuracy: 0.3333 - val_loss: 1.0384
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6000 - loss: 0.5896 - val_accuracy: 0.3333 - val_loss: 0.9213
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6000 - loss: 0.6210 - val_accuracy: 0.3333 - val_loss: 0.9723