In [2]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_csv("country.csv")
data.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [4]:
# country with highest population
data[data['population'] == data['population'].max()][['country', "population" , "capital_city"]]

   country  population capital_city
75   India  1417173173    New Delhi

In [5]:
data[data['population'] == data['population'].min()][['country', "population" , "capital_city"]]

    country  population capital_city
179  Tuvalu       11312     Funafuti

In [11]:
# Top 5 countries with highest democracy_score
data.nlargest(5,"democracy_score")[['country',"democracy_score"]]

         country  democracy_score
127       Norway             9.87
74       Iceland             9.58
164       Sweden             9.39
122  New Zealand             9.26
46       Denmark             9.22

In [32]:
# Total regions
for i,j in data.groupby("region"):
    print(i , end=" , ",)
data['region'].value_counts().count()

Australia and New Zealand , Caribbean , Central America , Central Asia , Eastern Africa , Eastern Asia , Eastern Europe , Melanesia , Micronesia , Middle Africa , Northern Africa , Northern America , Northern Europe , Polynesia , South America , South-Eastern Asia , Southern Africa , Southern Asia , Southern Europe , Western Africa , Western Asia , Western Europe ,

np.int64(22)

In [35]:
# How many countries lie in Eastern Europe Region
data[data['region'] == "Eastern Europe"][['country']]
data['region'].value_counts()['Eastern Europe']

np.int64(10)

In [25]:
# Leader of 2nd largest population country
data.nlargest(2,"population").iloc[-1][['country', "population" , "capital_city","political_leader","title"]]

country                                                China
population                                        1412175000
capital_city                                         Beijing
political_leader                                  Xi Jinping
title               General Secretary of the Communist Party
Name: 34, dtype: object

In [45]:
# Unknown leaders
data[data['political_leader'].isna()]['country']

27                         Cabo Verde
151                   Slovak Republic
159               St. Kitts and Nevis
160                         St. Lucia
161    St. Vincent and the Grenadines
172                       Timor-Leste
190                West Bank and Gaza
Name: country, dtype: str

In [56]:
# Republic in name cpuntries
count = 0
def rc(txt):
    global count
    for i in txt:
        if("republic" in txt.lower()):
            count+=1
    return txt
data['country'].apply(rc)
count

106